version: '3'

services:
  node1:    #后台服务1 TODO:1.打算一组前端和后端应用程序放一台服务器上，2.应用程序的nginx负载均衡
    image: "node:alpine"
    user: "node"
    container_name: node1
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: "npm start"
  mysql1:    #数据库1 TODO:1.数据库的pxc分布式集群，2.haproxy负载均衡
    image: mysql:5.7.27
    container_name: mysql1
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #85021687
      MYSQL_DATABASE: grandway_product_db
    ports:
      - "3306:3306"
  mysql2:    #数据库2 
    image: mysql:5.7.27
    container_name: mysql2
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #85021687
      MYSQL_DATABASE: grandway_product_db
    ports:
      - "3307:3306"
  mysql3:    #数据库3
    image: mysql:5.7.27
    container_name: mysql3
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #85021687
      MYSQL_DATABASE: grandway_product_db
    ports:
      - "3308:3306" 
  adminer:    #数据库管理
    image: adminer  
    container_name: adminer
    ports:      
      - "8080:8080"
